runtime: php55
runtime_config:
  document_root: .
api_version: 1

handlers:

- url: /
  script: index.php

# Serve images as static resources.
- url: /(.+\.(gif|png|css|js|jpg|jpeg|png|ico|svg|woff2|ttf))$
  static_files: \1
  upload: .+\.(gif|png|css|js|jpg|jpeg|png|ico|svg|woff2|ttf)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1




env_variables:
  CLOUDSQL_USER: root
  CLOUDSQL_DB: login_system
  CLOUDSQL_PASSWORD: qwe123
  CLOUDSQL_DSN: /cloudsql/job-match-pp:australia-southeast1:job-instance